### ISSUE TITLE
suggestion: add restart command

### ISSUE THREAD

**Issue by yukulele** [mactkg/vscode-sonic-pi#13]
when i select "run code on sonic-pi" it play it over currently played.
to avoid it I have to select "stop all sound on sonic-pi" then "run code on sonic-pi", each time.

It could be useful to have a "stop all and run code on sonic-pi" command

**Comment by mactkg** [comment]
I'll close this issue when I published new version that is included #14.

**Comment by mactkg** [comment]
Published at 0.1.0. https://marketplace.visualstudio.com/items?itemName=mactkg.sonic-pi
