### ISSUE TITLE
Question : commands to stop , to reload ?

### ISSUE THREAD

**Issue by nlebellier** [mactkg/vscode-sonic-pi#21]
Hi,

is there a command to stop within vscode ?

**Comment by cassiebreviu** [comment]
You can create your own shortcuts - there isnt one by default. 

Go to VS Code menu Preferences-->Keyboard Shortcuts to create a shortcut.

I used:

Run: ctrl+shirt + r+r
stop and run: ctrl+shift s +r
stop all: ctrl+shift+s + s

**Comment by nlebellier** [comment]
yep
