### ISSUE TITLE
Latest SPdev no longer uses port 4557

### ISSUE THREAD

**Issue by rbnpi** [mactkg/vscode-sonic-pi#3]
Recent changes to the source code of SP means that the previous port 4557 is now dynamically allocated at run time, so communicating to port 4557 no longer will work.
FWIW I have looked at the same problem with sonic-pi-cli gem and I have developed a mechanism to detect the dynamic port in use  by reading it from the SP logs which might be applied here.
see this PR https://github.com/Widdershin/sonic-pi-cli/pull/21 for details.

**Comment by mactkg** [comment]
Thanks for your sharing!  I'll take a look later.(PR is welcome!)

**Comment by mogimogitomato** [comment]
Hooray! Sonic Pi 3.2 released!!
I fixed this issue by detect the dynamic listen port from Sonic Pi's gui.log(thank you @rbnpi ),
and checked the operation in the following environment.

- Mac OS Catalina , Sonic Pi 3.2
- Mac OS Catalina , Sonic Pi 3.1
- Windows 10 , Sonic Pi 3.2
- Windows 10 , Sonic Pi 3.1
- Ubuntu 19.04 , Sonic Pi 2.10(latest package ion the launch pad)

It's operation is OK, so I send PR. Best regards.

**Comment by mactkg** [comment]
Thank you :sob:

**Comment by mactkg** [comment]
This issue should be resolved in 0.3.0.
